<?php
/**
 * Created by PhpStorm.
 * User: Akin
 * Date: 2018/1/23
 * Time: 3:17
 */
namespace  app\admin\controller;
use think\Controller;
use think\Request;

 class  Base extends  Controller
{
    protected $is_check_login = [''];
    public function  _initialize()
    {
        if (!session('name'))
        {
            if(!$this->isLogin() && (in_array(Request::instance()->action(),$this->is_check_login)||$this->is_check_login[0]=='*')){
                $this->error('请先登录系统','admin/Index/index');
            }


        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function isLogin()
    {
        return session('?name');

    }









}
