<?php
/**
 * Created by PhpStorm.
 * User: Akin
 * Date: 2018/1/23
 * Time: 3:17
 */
namespace  app\admin\controller;

use think\Controller;
use think\Request;
use think\auth\Auth;
 class  Base extends  Controller
{
    protected $is_check_login = [''];
     protected $is_check_auth = [''];
    public function  _initialize()
    {
        define('CONTROLLER_NAME',Request::instance()->controller());
        define('ACTION_NAME',Request::instance()->action());
        if (!session('name'))
        {
            if(!$this->isLogin() && (in_array(Request::instance()->action(),$this->is_check_login)||$this->is_check_login[0]=='*')){
                $this->error('请先登录系统','/');
            }
        }
        if (!$this->haveAuth()) {
            if ((in_array(Request::instance()->action(), $this->is_check_auth) || $this->is_check_auth[0] == '*')) {
                $this->error('权限不足');
            }
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function isLogin()
    {
        return session('?name');

    }

    public function haveAuth(){
        $auth = new auth();
        $checkAuth = $auth->check(CONTROLLER_NAME.'/'.ACTION_NAME,input('session.user_id'));
        return $checkAuth;
    }
     public function my_serialize( $obj )

     {

         return base64_encode(json_encode($obj));

     }

     function my_unSerialize($txt)

     {

         return json_decode(base64_decode($txt),true);

     }



}
